apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: all-cluster-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: reader-global
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: all-cluster-reader
subjects:
- kind: Group
  name: system:serviceaccounts:prometheus
  namespace: prometheus
